replicaCount: 1

image:
  repository: data-zoo/query_api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8005

probes:
  liveness:
    path: /health
  readiness:
    path: /readyz

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

env:
  environment: local

secrets:
  name: data-zoo-app-secrets
  databaseUrlKey: database_url
