"""add_processed_events_and_records_unique_constraint

Revision ID: a326ea4bd1da
Revises: a8f3c2e9d1b4
Create Date: 2026-04-21 19:03:43.911337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a326ea4bd1da'
down_revision: Union[str, Sequence[str], None] = 'b770f07991cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kafka_topic', sa.String(length=255), nullable=False),
    sa.Column('kafka_partition', sa.Integer(), nullable=False),
    sa.Column('kafka_offset', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('processing_attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('dead_letter_queue', sa.Boolean(), nullable=False),
    sa.Column('dlq_reason', sa.String(length=500), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_dead_letter_queue', 'processed_events', ['dead_letter_queue'], unique=False)
    op.create_index('ix_events_idempotency_key', 'processed_events', ['idempotency_key'], unique=True)
    op.create_index('ix_events_kafka_offset', 'processed_events', ['kafka_offset'], unique=False)
    op.create_index('ix_events_status', 'processed_events', ['status'], unique=False)
    op.create_unique_constraint('uq_records_source_timestamp', 'records', ['source', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_records_source_timestamp', 'records', type_='unique')
    op.drop_index('ix_events_status', table_name='processed_events')
    op.drop_index('ix_events_kafka_offset', table_name='processed_events')
    op.drop_index('ix_events_idempotency_key', table_name='processed_events')
    op.drop_index('ix_events_dead_letter_queue', table_name='processed_events')
    op.drop_table('processed_events')
    # ### end Alembic commands ###
