"""add_processed_at_column

Revision ID: b770f07991cf
Revises: 3343a3d6c4b7
Create Date: 2026-04-18 02:14:13.656624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b770f07991cf'
down_revision: Union[str, Sequence[str], None] = '3343a3d6c4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    # Backfill: set processed_at = created_at for existing processed records
    op.execute(
        "UPDATE records SET processed_at = created_at WHERE processed = true AND processed_at IS NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'processed_at')
    # ### end Alembic commands ###
