"""add_indexes_timestamp_processed

Revision ID: 3343a3d6c4b7
Revises: 21878e22a57b
Create Date: 2026-04-18 01:57:41.498366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3343a3d6c4b7'
down_revision: Union[str, Sequence[str], None] = '21878e22a57b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_records_processed', 'records', ['processed'], unique=False)
    op.create_index('ix_records_timestamp', 'records', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_records_timestamp', table_name='records')
    op.drop_index('ix_records_processed', table_name='records')
    # ### end Alembic commands ###
