apiVersion: v1
kind: Service
metadata:
  name: ingestor
  labels:
    app.kubernetes.io/name: ingestor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ingestor
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
