apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-ai-gateway
  namespace: data-zoo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ai-gateway
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingestor
