apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-egress-from-processor
  namespace: data-zoo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: processor
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redpanda
      ports:
        - port: 9092
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingestor
      ports:
        - port: 8000
          protocol: TCP
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
