apiVersion: v1
kind: Service
metadata:
  name: inference
  labels:
    app.kubernetes.io/name: inference
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: inference
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
