apiVersion: v1
kind: Service
metadata:
  name: analytics
  labels:
    app.kubernetes.io/name: analytics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: analytics
  ports:
    - name: http
      port: 8005
      targetPort: http
      protocol: TCP
