apiVersion: v1
kind: Service
metadata:
  name: processor
  labels:
    app.kubernetes.io/name: processor
    app.kubernetes.io/component: consumer
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: processor
  ports:
    - name: http
      port: 8002
      targetPort: http
      protocol: TCP
